### ISSUE TITLE
testing function which returns multiple arrays with different sizes

### ISSUE THREAD

**Issue by amine-aboufirass** [astropy/pytest-arraydiff#19]
This seems like a nice plugin, but what if I have functions that return multiple arrays with different shapes, i.e:

```
import numpy as np

def f():
    return np.array([1,2,3]), np.array([1,2,3,4])
```

How do I test that the returned arrays are correct? Thanks.

**Comment by awa5114** [comment]
hello?

**Comment by nstarman** [comment]
Does an object array work instead?


```
import numpy as np

def f():
    return np.array([np.array([1,2,3]), np.array([1,2,3,4])], dtype=object)
```

**Comment by pllim** [comment]
Since there was no reply, closing the issue. Feel free to reopen if still not resolved. Thanks!
