### ISSUE TITLE
Version on conda-forge is out of date

### ISSUE THREAD

**Issue by dstansby** [astropy/pytest-arraydiff#37]
The latest version on https://anaconda.org/conda-forge/pytest-arraydiff is 0.3, but it looks like the most recent version of `pytest-arraydiff` is 0.5. Would be great if it could be updated on conda-forge!

**Comment by bsipocz** [comment]
https://github.com/conda-forge/pytest-arraydiff-feedstock/pull/4 needs to be merged, @mwcraig or @astrofrog can do that.

**Comment by atharva-2001** [comment]
Any updates on this?

**Comment by pllim** [comment]
Try to pip install for now.

**Comment by pllim** [comment]
Should be on conda-forge soon. 🤞 

Thanks, everyone!
