### ISSUE TITLE
Test outputs are not being correctly verified

### ISSUE THREAD

**Issue by larrybradley** [astropy/pytest-arraydiff#40]
As an example, I removed a test output file and deliberately changed some values in some output files. 
 The resulting tests should fail, but they do not:  https://github.com/astropy/regions/pull/515

**Comment by moux233** [comment]
Hi
Same for me
Related to pytest 7 and new warning:
PytestReturnNotNoneWarning: Expected None, but mypackage/tests/test_sensors.py::TestFilters::test_embeddedfilter1 returned array([[ myarray    ]]), which will be an error in a future version of pytest.  Did you mean to use `assert` instead of `return`?
Reverting to pytest 6

**Comment by pllim** [comment]
I am guessing you were not using a dev version of pytest-arraydiff? I just released v0.6.0 . Can you please upgrade and see if it works now?

**Comment by moux233** [comment]
Thank you. Indeed I was using pytest-arraydiff 0.5.0.
I tested pytest-arraydiff 0.6.0 with pytest 7.4.3 this morning, it works perfectly fine. I tested both reference generation and checking.

**Comment by pllim** [comment]
@larrybradley 's current problem is specifically with tox not able to find the reference directory.

**Comment by moux233** [comment]
hmm sounds familiar
my suggestion would be to check the setup.cfg data:

[options.package_data]
* =	tests/reference/*

**Comment by larrybradley** [comment]
@moux233 That was my initial thought too, but the reference data are being packaged.
https://github.com/astropy/regions/blob/main/pyproject.toml#L81

**Comment by larrybradley** [comment]
I fixed the issue -- there was a typo in `pyproject.toml` `package-data`.  🤦   Sorry for the noise.
