### ISSUE TITLE
Bug: single_reference=True not working currently

### ISSUE THREAD

**Issue by astrofrog** [astropy/pytest-arraydiff#42]
I think a bug has been introduced with the recent release - reproject makes use of the ``single_reference=True`` option but this doesn't appear to be working anymore in the last few days:

https://github.com/astropy/reproject/actions/runs/6854228148/job/18815976303

Example error:

```
E               Exception: File not found for comparison test
E                                               Generated file:
E                                               	/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmp8ftf61xs/test_reproject_roundtrip[asdf].fits
E                                               This is expected for new tests.
```

but the reference file should be ``test_reproject_roundtrip.fits`` not ``test_reproject_roundtrip[asdf].fits``

**Comment by astrofrog** [comment]
I wonder whether this is related to https://github.com/astropy/pytest-arraydiff/pull/36? (cc @ConorMacBride)

**Comment by ConorMacBride** [comment]
Yes, it's related to a bug in that PR. When the single reference option option is enabled it's generating the file name using `item.name` instead of `item.function`. Should be a quick fix. I'll try to get that in next week, unless someone gets there before me!

**Comment by pllim** [comment]
Like this? https://github.com/astropy/pytest-arraydiff/pull/43

Not sure how this repo handle milestone, so feel free to re-milestone and fix up the change log.
